const PRIMARY_PURPLE = "#635D9D";
const PRIMARY_RED = "#FD5358";
const PRIMARY_GOLD = "#FFB548";
const PRIMARY_BLACK = "#171F21";
const PRIMARY_OFF_WHITE = "#FFFBF4";
const PRIMARY_WHITE = "#FFFFFF";
const SECONDARY_TEAL = "#A8DADB";
const SECONDARY_BLUE = "#457B9D";
const SECONDARY_DARK_GRAY = "#828282";
const SECONDARY_GRAY = "#BDBDBD";
const SECONDARY_LIGHT_GRAY = "#E0E0E0";


const colors = {
  PRIMARY_PURPLE,
  PRIMARY_RED,
  PRIMARY_GOLD,
  PRIMARY_BLACK,
  PRIMARY_OFF_WHITE,
  PRIMARY_WHITE,
  SECONDARY_TEAL,
  SECONDARY_BLUE,
  SECONDARY_DARK_GRAY,
  SECONDARY_GRAY,
  SECONDARY_LIGHT_GRAY
}

export default colors;